spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore?serverTimezone=Asia/Shanghai
    username: root
    password: 1212
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.atguigu.entity
logging:
  level:
    com.atguigu.mapper: debug